import { Roboto, Geist_Mono, Jura, Farsan, Inconsolata, Monda } from "next/font/google";
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import "./globals.css";

// Mengimpor font Monda, Inconsolata, Farsan, Jura, Roboto, dan Geist_Mono
const monda = Monda({
  subsets: ['latin'],
  weight: '400', // Kamu bisa memilih berat font sesuai kebutuhan
});

const inconsolata = Inconsolata({
  subsets: ['latin'],
  weight: '400',
});

const farsan = Farsan({
  subsets: ['latin'],
  weight: '400',
});

const jura = Jura({
  subsets: ['latin'],
  weight: '400',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: '400',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ['latin'],
});

config.autoAddCss = false;

export const metadata = {
  title: "Invic Production",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={monda.className}>
      <body className={`${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
